# Generated by Django 4.1.6 on 2023-10-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberland.driver'),
        ),
        migrations.AlterField(
            model_name='recieveride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberland.passenger'),
        ),
    ]
