# Generated by Django 4.1.6 on 2023-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0002_alter_recieveride_driver_alter_recieveride_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveride',
            name='driver',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='recieveride',
            name='passenger',
            field=models.CharField(max_length=37),
        ),
    ]
