# Generated by Django 4.1.6 on 2023-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0004_alter_recieveride_driver_alter_recieveride_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_location',
            field=models.CharField(max_length=37, null=True),
        ),
    ]
