# Generated by Django 4.1.6 on 2023-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0005_ride_departure_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
