# Generated by Django 4.1.6 on 2023-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0006_alter_ride_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
