# Generated by Django 4.1.6 on 2023-10-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0007_ride_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=37, null=True)),
                ('destination_location', models.CharField(max_length=37, null=True)),
                ('emission', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uberland.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberland.passenger')),
            ],
        ),
    ]
