# Generated by Django 4.1.6 on 2023-10-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberland', '0008_finishedride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
